image: Visual Studio 2017

configuration:
  - Release

platform:
  - x86
  - x64

environment:
  VCVARS: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat
  PYTHON: "C:\\Python38-x64"
  SHARED: ON

shallow_clone: true

install:
    - ps: $env:EXIV2_VERSION=$(sed -n 's@^ *VERSION \+\(.*\)@\1@p' CMakeLists.txt)
    - echo %EXIV2_VERSION%
    - set PATH=%PYTHON%;%PATH%;%PYTHON%/Scripts/
    - echo %APPVEYOR_BUILD_FOLDER%
    - if not exist deps mkdir deps
    - cd deps
    - if not exist ninja appveyor DownloadFile https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-win.zip -FileName ninja.zip
    - if not exist ninja 7z x ninja.zip -o%APPVEYOR_BUILD_FOLDER%\deps\ninja > nul
    - set PATH=%APPVEYOR_BUILD_FOLDER%\deps\ninja;%PATH%
    - ninja --version
    - python -m pip install --upgrade pip
    - pip3.exe install conan==1.59.0
    - pip3.exe install lxml
    - cd %APPVEYOR_BUILD_FOLDER%

before_build:
    - cmd: conan remote list
    - cmd: conan config set storage.path=c:\Users\appveyor\conanCache
    - cmd: conan profile new --detect default
    - cmd: conan profile update settings.compiler.version=15 default
    - cmd: if "%platform%"=="x64" (set ARCHITECTURE=x86_64) else (set ARCHITECTURE=x86)
    - cmd: if "%CONFIGURATION%"=="Debug" (set RUNTIME=MDd) else (set RUNTIME=MD)
    - cmd: conan profile update settings.arch=%ARCHITECTURE% default
    - cmd: conan profile update settings.arch_build=%ARCHITECTURE% default
    - cmd: conan profile update settings.build_type=%CONFIGURATION% default
    - cmd: conan profile update settings.compiler.runtime=%RUNTIME% default
    - cmd: cat c:\Users\appveyor\.conan\conan.conf
    - cmd: cat c:\Users\appveyor\.conan\profiles\default

build_script:
    - cmd: md build
    - cmd: cd build
    - cmd: if "%platform%"=="x64" (set VC_ARCH=x86_amd64) else (set VC_ARCH=x86)
    - cmd: if "%platform%"=="x64" (set EXIV2_PLATFORM=2017msvc64) else (set EXIV2_PLATFORM=2017msvc32)
    - cmd: call "%VCVARS%" %VC_ARCH%
    - cmd: conan install .. --build missing -o webready=True
    - cmd: cmake -GNinja -DBUILD_SHARED_LIBS=%SHARED% -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DEXIV2_ENABLE_NLS=OFF -DEXIV2_ENABLE_PNG=ON -DEXIV2_ENABLE_WEBREADY=OFF -DEXIV2_ENABLE_CURL=OFF -DEXIV2_BUILD_UNIT_TESTS=ON -DEXIV2_BUILD_SAMPLES=ON -DEXIV2_ENABLE_BMFF=ON -DCMAKE_INSTALL_PREFIX=exiv2-%EXIV2_VERSION%-%EXIV2_PLATFORM% ..
    - cmd: ninja
    - cmd: ninja install
    - cmd: 7z a exiv2-%EXIV2_VERSION%-%EXIV2_PLATFORM%.zip exiv2-%EXIV2_VERSION%-%EXIV2_PLATFORM%
    - cmd: appveyor PushArtifact exiv2-%EXIV2_VERSION%-%EXIV2_PLATFORM%.zip
    - cmd: cd bin
    - cmd: unit_tests.exe
    - cmd: cd ../../tests/
    - cmd: set EXIV2_EXT=.exe
    - cmd: python.exe runner.py -v

cache:
- deps                          # Ninja installation
- c:\Users\appveyor\conanCache  # Conan cache
