# Basic CI for all platforms on push
# Note that we want to run this as fast as possible and just for the more common configurations. On
# PRs, we will test things more intensively :)
# - Only running UnitTests and not regression tests

on:
  push:
    paths-ignore:
      - "*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: On PUSH - Basic CI for main platforms

jobs:
  windows:
    name: 'Win10 Arch:x64 BuildType:Release - SHARED'
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3

      - name: Set up Visual Studio shell
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Restore conan cache
        uses: actions/cache@v3
        with:
            path: ${{github.workspace}}/conanCache
            key: ${{runner.os}}-push-win-${{ hashFiles('conanfile.py') }}

      - name: Install Conan & Common config
        run: |
          python -m pip install conan==1.59.0
          conan profile new --detect default
          conan profile show default
          conan profile update settings.compiler="Visual Studio" default
          conan profile update settings.compiler.version=17 default
          conan config set storage.path=$Env:GITHUB_WORKSPACE/conanCache

      - name: Build
        run: |
          cmake --preset win-release -S . -B build
          cmake --build build --parallel


      - name: Test
        run: |
          cd build
          ctest --output-on-failure
